<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Резюме')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
         <div class="container">  
        <div class="row">
            <!-- Заголовок страницы -->
            <div class="col-md-12">
                <div class="app-caption">Напсиков Олег</div>
            </div>                
        </div>
     
        
        <div class="row">
            <div class="col-md-12">
                <!-- Плейсхолдер для содержимого страницы -->
                <?= $this->content; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <hr>                
                <span class="align-top">Связаться со мной: <img src="img/8fe8711301feae4bd4db43bb83760a67.gif" ></span>
            </div>
    </div> <!-- /container -->         
        <?= $this->inlineScript()
           /* ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) */?>
    </body>
</html>
