<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Резюме')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
         <div class="container">  
        <div class="row">
            <!-- Заголовок страницы -->
            <div class="col-md-4">
                <div class="app-caption">Hello World!</div>
            </div>                
        </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>         
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav nav-tabs">
      <li class="nav-item active">
        <a class="nav-link" href="<?= $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?= $this->url('about') ?>">About</a>
      </li>
        
    </ul>
    </div>
</nav>     
        
        <div class="row">
            <div class="col-md-12">
                <!-- Плейсхолдер для содержимого страницы -->
                <?= $this->content; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <hr>                
                <p>&copy; 2005 - <?= date('Y') ?> by Your Company. All rights reserved.</p>
            </div>
    </div> <!-- /container -->         
        <?= $this->inlineScript()
           /* ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) */?>
    </body>
</html>
