<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="text-center" >Резюме</h1>
    </br>
    <h3 class="text-center" >Образование</h3>
    </br>
    <p>
        Ярославский государственный университет им. П. Г. Демидова,экономический факультет.
    </p>
    <h3 class="text-center" >Навыки</h3>
    </br>
    <p>
        PHP,HTML 5,CSS,MVC Zend 3,Bootstrap,NetBeans IDE,Visual Studio
    </p>    
   <h3 class="text-center" >Опыт работы</h3>
   </br>
   

<table  class="table table-bordered">
    <tr>
        <th>Период работы</th>
        <th>Работодатель</th>
        <th>Должность</th>
    </tr>

    <?php 
        foreach($this->products as $product) {
            echo $this->partial('application/index/table-row', ['product'=>$product]);
        }    
    ?>    
</table> 

    
</div>


